# Generated by Django 5.0.4 on 2024-07-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_student_classroom_alter_student_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classroom',
            new_name='class_room',
        ),
    ]
