# Generated by Django 5.0.4 on 2024-07-02 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_classroom_student_class_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeroomteacher',
            name='class_room_code',
        ),
        migrations.RemoveField(
            model_name='homeroomteacher',
            name='teacher_code',
        ),
        migrations.AddField(
            model_name='homeroomteacher',
            name='class_room',
            field=models.ForeignKey(default=234567, on_delete=django.db.models.deletion.CASCADE, to='apis.classroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeroomteacher',
            name='teacher',
            field=models.ForeignKey(default=233333, on_delete=django.db.models.deletion.CASCADE, to='apis.teacher'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='homeroomteacher',
            table='home_room',
        ),
    ]
